<?php /** @var $this MKleine_Helpcustomers_Block_Stocknotification_Add */ ?>

<h1><?php echo $this->__('Product notification'); ?></h1>

<?php if($product = $this->getProduct()) : ?>

    <p><strong><?php echo $this->__('Successfully registered'); ?>:</strong> <?php echo $product->getName(); ?> (<?php echo $product->getSku(); ?>)</p>
    <p><?php echo $this->__('You will be informed by mail if the product is available'); ?></p>

    <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $this->__('Back to product'); ?></a>
<?php endif; ?>